server:
  port: 80
eureka:
  client:
    # 注册自己
    register-with-eureka: true
    # 是否从注册中心抓取服务信息 用于负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true

spring:
  application:
    name: cloud-order-service
logging:
  level:
    com.sub.service.PaymentService: debug
